### ISSUE TITLE
'default' value can not be set if it's not in the list.

### ISSUE THREAD

**Issue by zpengyu** [thetron/mongoid-enum#7]
I have the code like
`enum :gender, [:male, :female], default: ''`
doesn't work.

If I don't set a value, I got 
`The following errors were found:  gender is not included in the list`

**Comment by thetron** [comment]
I've finally gotten around to looking through this issue in detail and @p3drosola got this one right - if you want to allow nil values, then passing an option of `required: false` is the way to go. It might be worth renaming this in the future to `allow_nil`, to make it a bit more consistent with the Rails API though.

@hoang1417 If you do have an edge case where the default value is mysteriously required to _not_ be in the list of options, then you're probably best off disabling validations and rolling your own solution that works.

Hope this answers everyone's questions - if I've missed the point completely, feel free to add to the discussion and i'll reopen the issue :smile:
