### ISSUE TITLE
Saving a multiple enum

### ISSUE THREAD

**Issue by senorpasajero** [thetron/mongoid-enum#9]
Hi Thetron,

I just have a simple question, I have an enum with option multiple equal to true. What is the correct way to send the params for autosave?

I mean my form is sending day => [ 'day1', 'day2' ] but the i have error with the validation.

**Comment by thetron** [comment]
@senorpasajero Thanks for this - I know this response is super late, but this was (kinda) a bug, and will be resolved in the next version (due in the next couple of days). :beers:
